### ISSUE TITLE
[RFC] Use capistrano as Farmer's deploy strategy

### ISSUE THREAD

**Issue by aramalipoor** [farmer-project/farmer#63]
I'm not sure if their philosophy matches ours but anyway if it could help us to stay DRY it can be a good decision.

Some things to consider:
* Revisions and rollback process should match farmer's architecture. (Code is managed outside of the app's container)
* Post-deploy actions should be easy to create and run inside the app's container.
* All in all it should not add complexity to Farmer and should work with `Capfile`s out-of-the-box, so that users can easily make use of it without the need to tweak Capfile to farmer's architecture.

**Comment by majidgolshadi** [comment]
Capistrano is written in Ruby and our project is on Go lang so i think we can't use that in stable way but as you mention it's contains some good idea that we try to use them in out project.
